"use client";

// =============================================================================
// Cohort Signals — Phase 6 Feature 4
// =============================================================================
// Dashboard cards showing cohort-level activity insights.
// Generated by AI from discussion + event data, cached for 24 hours.
// =============================================================================

import Link from "next/link";
import { FeaturePreview } from "@/app/components/ui/FeaturePreview";

interface CohortSignal {
    signalType: "most_discussed" | "common_pattern" | "top_takeaway";
    title: string;
    description: string;
    episodeId?: string;
    episodeTitle?: string;
}

interface CohortSignalsProps {
    signals: CohortSignal[] | null;
}

const SIGNAL_ICONS: Record<string, string> = {
    most_discussed: "🔥",
    common_pattern: "📊",
    top_takeaway: "💡",
};

export function CohortSignals({ signals }: CohortSignalsProps) {
    if (!signals || signals.length === 0) {
        return (
            <FeaturePreview
                icon="📡"
                title="Cohort Activity"
                description="Cohort activity insights will appear here as participants engage with episodes and discussions."
                badge="AI"
            />
        );
    }


    return (
        <div style={{ marginTop: "1.5rem" }}>
            <div className="workspace-section-label" style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
                <span>📡</span>
                <span>Cohort Activity</span>
                <span
                    style={{
                        fontSize: "0.65rem",
                        background: "var(--brand-orange-glow)",
                        color: "var(--brand-orange-light)",
                        padding: "0.15rem 0.5rem",
                        borderRadius: "var(--radius-sm)",
                        fontWeight: 600,
                    }}
                >
                    AI
                </span>
            </div>
            <div style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(14rem, 1fr))",
                gap: "0.75rem",
                marginTop: "0.75rem",
            }}>
                {signals.map((signal, i) => (
                    <div
                        key={i}
                        style={{
                            padding: "1rem",
                            background: "var(--bg-secondary)",
                            borderRadius: "var(--radius-md)",
                            border: "1px solid var(--border-subtle)",
                        }}
                    >
                        <div style={{
                            display: "flex",
                            alignItems: "center",
                            gap: "0.5rem",
                            marginBottom: "0.4rem",
                        }}>
                            <span style={{ fontSize: "1rem" }}>{SIGNAL_ICONS[signal.signalType] ?? "📊"}</span>
                            <span style={{
                                fontSize: "0.8rem",
                                fontWeight: 700,
                                color: "var(--text-primary)",
                            }}>
                                {signal.title}
                            </span>
                        </div>
                        <p style={{
                            fontSize: "0.75rem",
                            lineHeight: 1.5,
                            color: "var(--text-secondary)",
                            margin: 0,
                        }}>
                            {signal.description}
                        </p>
                        {signal.episodeId && (
                            <Link
                                href={`/episodes/${signal.episodeId}`}
                                style={{
                                    display: "inline-block",
                                    marginTop: "0.5rem",
                                    fontSize: "0.7rem",
                                    color: "var(--brand-orange)",
                                    fontWeight: 600,
                                    textDecoration: "none",
                                }}
                            >
                                View Episode →
                            </Link>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
}
